### ISSUE TITLE
Implementing setter in interface when only getter is set.

### ISSUE THREAD

**Issue by klowdo** [CodingFlow/decorator-generator#39]
Given code: 
``` c#
[Decorate]
public interface ICat
{
    public string Value { get; }
}
```

will generate :
```c#
public abstract class CatDecorator : ICat
{
    private ICat cat;

    protected CatDecorator(ICat cat) {
        this.cat = cat;
    }

    public virtual string Value { get => cat.Value; set => cat.Value = value; }


}

```

And will fail on setter.

Version: 0.2.1

And great library!!!

**Comment by CodingFlow** [comment]
Hi @klowdo Thank you for reporting the issue! I've merged the fix and published a [new version 0.2.2 to nuget.org](https://www.nuget.org/packages/DecoratorGenerator/0.2.2). Try it out and feel free to close this Issue if the bug is fixed.
